version: '3'
services:
  conductor:
    image: danielgerlag/conductor
    ports:
    - "5001:80"
    links:
    - mongo
    environment:
      dbhost: mongodb+srv://wfuser:logo12Q2@pdf4mecluster-zhvoy.azure.mongodb.net/test?retryWrites=true&w=majority
      dbuser: wfuser
      dbpass: logo12Q2
      redis: dmscacheq1.redis.cache.windows.net:6380,password=qKccuJsH6l+vy14KQdvy3DRLPLnLPL2NaTPJsjH3+Gg=,ssl=True,abortConnect=False
  mongo:
    image: mongo
